apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}
  namespace: argocd
spec:
  destination:
    namespace: kargo-demo-3
    server: https://kubernetes.default.svc
  project: default
  sources:
    - helm:
        valueFiles:
          - values.yaml
      path: helm-appset
      repoURL: https://github.com/paritytech-stg/KargoDemo
      targetRevision: HEAD