apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $product }}-metaapp
  namespace: argocd
spec:
    project: default
    sources:
      - helm:
          path: helm-appset
          repoURL: https://github.com/paritytech-stg/KargoDemo
          targetRevision: HEAD
          valueFiles:
            - values.yaml
            #- $valuesRepo/values.yaml
            {{- range $product, $values := .Values.products }}
            - ${{ $product }}/values.yaml
            {{- end }}
          valuesObject:
    {{- range $product, $values := .Values.products }}
      - repoURL: {{ $values.repo }}
        targetRevision: HEAD
        ref: {{ $product }}
    {{- end }}