{{- range $productName, $val := .Values.products }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  annotations:
    kargo.akuity.io/create-actor: admin
  name: {{ $productName }}

{{- end }}