apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
spec:
  promotionTemplate:
    spec:
      steps:
        - as: argo-update
          config:
            apps:
              - name: {{ .Values.productName }}-staging
                sources:
                  - helm:
                      images:
{{- if .Values.images }}
{{- range $name, $img := .Values.images }}
                        - key: images.{{ $name }}.image
                          value: {{ "${{" }} imageFrom("{{ $.Values.registry }}/{{ $name }}").RepoURL {{ "}}" }}:{{ "${{" }}imageFrom("{{ $.Values.registry }}/{{ $name }}").Tag {{ "}}" }}
{{- end }}
{{- end }}
                    repoURL: {{ .Values.repoURL }}
          continueOnError: false
          if: ""
          uses: argocd-update
  requestedFreight:
    - origin:
        kind: Warehouse
        name: {{ .Values.productName }}
      sources:
        direct: true
        stages: []