{{- range $productName, $val := .Values.products }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: {{ $productName }}
spec:
  freightCreationPolicy: Automatic
  interval: 1m0s
  subscriptions:
{{- if .Values.images }}
{{- range $name, $img := .Values.images }}
    - image:
        constraint: latest
        discoveryLimit: 3
        imageSelectionStrategy: Digest
        repoURL: {{ $.Values.registry }}/{{ $name }}
        strictSemvers: true
{{- end }}
{{- end }}

{{- end }}